"""Initial Database Schema Migration

Revision ID: 3f3d24e8f641
Revises: b6d6d87a7d62
Create Date: 2024-07-11 19:25:56.897375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3d24e8f641'
down_revision: Union[str, None] = 'b6d6d87a7d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
