"""empty message

Revision ID: 58f93cd675b1
Revises: b632d122c008
Create Date: 2024-06-19 19:50:39.674209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f93cd675b1'
down_revision: Union[str, None] = 'b632d122c008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
