"""empty message

Revision ID: 5bd63b9ed5ef
Revises: 34aa3c3b7e47
Create Date: 2024-01-27 08:22:51.155358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd63b9ed5ef'
down_revision: Union[str, None] = '34aa3c3b7e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registers', 'is_active')
    # ### end Alembic commands ###
