"""empty message

Revision ID: 67e2bf1afc4c
Revises: a28dfd9c219b
Create Date: 2024-06-23 10:03:28.548825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e2bf1afc4c'
down_revision: Union[str, None] = 'a28dfd9c219b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
