"""empty message

Revision ID: 69aa7a0e59d2
Revises: f9d420867177
Create Date: 2024-07-04 06:13:54.342403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69aa7a0e59d2'
down_revision: Union[str, None] = 'f9d420867177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('designation', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
