"""empty message

Revision ID: 984bb0a5e281
Revises: c9d6b39429cd
Create Date: 2024-06-19 16:54:06.843571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984bb0a5e281'
down_revision: Union[str, None] = 'c9d6b39429cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'note')
    # ### end Alembic commands ###
