"""empty message

Revision ID: b3e7567908d0
Revises: bdac20968064
Create Date: 2024-07-07 16:02:37.589549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e7567908d0'
down_revision: Union[str, None] = 'bdac20968064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('designation', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
