"""empty message

Revision ID: b632d122c008
Revises: 960edcf0efc2
Create Date: 2024-06-19 18:42:36.945416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b632d122c008'
down_revision: Union[str, None] = '960edcf0efc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'note')
    # ### end Alembic commands ###
