"""empty message

Revision ID: c4a226089076
Revises: 31f88d3dadc5
Create Date: 2024-07-10 18:53:32.873718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a226089076'
down_revision: Union[str, None] = '31f88d3dadc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('designation', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
